# Generated by Django 2.2.6 on 2019-12-19 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191219_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 14, 55, 10, 746847), verbose_name='date published'),
        ),
    ]
